improved sketchybar

diff --git a/private_dot_config/sketchybar/executable_sketchybarrc b/private_dot_config/sketchybar/executable_sketchybarrc
--- a/private_dot_config/sketchybar/executable_sketchybarrc
+++ b/private_dot_config/sketchybar/executable_sketchybarrc
@@ -1,24 +1,14 @@
-# This is a demo config to showcase some of the most important commands.
-# It is meant to be changed and configured, as it is intentionally kept sparse.
-# For a (much) more advanced configuration example see my dotfiles:
-# https://github.com/FelixKratz/dotfiles
+#!/bin/bash
 
-PLUGIN_DIR="$CONFIG_DIR/plugins"
+# This is a sketchybarrc file that uses Lua scripts instead of Bash scripts
+
+PLUGIN_DIR="$CONFIG_DIR/lua_plugins"
+BASH_PLUGIN_DIR="$CONFIG_DIR/plugins" # necessary for performance (example from demo, ensure this path is correct if you use it)
 
 ##### Bar Appearance #####
-# Configuring the general appearance of the bar.
-# These are only some of the options available. For all options see:
-# https://felixkratz.github.io/SketchyBar/config/bar
-# If you are looking for other colors, see the color picker:
-# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker
-
 sketchybar --bar position=top height=40 blur_radius=30 color=0x40000000
 
 ##### Changing Defaults #####
-# We now change some default values, which are applied to all further items.
-# For a full list of all available item properties see:
-# https://felixkratz.github.io/SketchyBar/config/items
-
 default=(
   padding_left=5
   padding_right=5
@@ -34,62 +24,48 @@ default=(
 sketchybar --default "${default[@]}"
 
 ##### Adding Mission Control Space Indicators #####
-# Let's add some mission control spaces:
-# https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item
-SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")
+SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10") # Ensure you have aerospace installed and configured if using this.
 sketchybar --add event aerospace_workspace_change
 
-for sid in $(aerospace list-workspaces --all); do
+# Check if aerospace command exists before trying to use it
+if command -v aerospace &> /dev/null; then
+  for sid in $(aerospace list-workspaces --all); do
     # Use icons from SPACE_ICONS array if available, otherwise use the sid as fallback
     icon_index=$((sid - 1))
-    if [ $icon_index -lt ${#SPACE_ICONS[@]} ]; then
+    if [ $icon_index -lt ${#SPACE_ICONS[@]} ] && [ $icon_index -ge 0 ]; then
         space_icon="${SPACE_ICONS[$icon_index]}"
     else
         space_icon="$sid"
     fi
 
     sketchybar --add item space.$sid left \
-        --subscribe space.$sid aerospace_workspace_change \
-        --set space.$sid \
-        background.color=0x40ffffff \
-        background.corner_radius=5 \
-        background.height=25 \
-        background.drawing=off \
-        icon="$space_icon" \
-        icon.padding_left=7 \
-        icon.padding_right=7 \
-        label.drawing=off \
-        click_script="aerospace workspace $sid" \
-        script="$CONFIG_DIR/plugins/aerospace.sh $sid"
-done
-##### Adding Left Items #####
-# We add some regular items to the left side of the bar, where
-# only the properties deviating from the current defaults need to be set
+      --subscribe space.$sid aerospace_workspace_change \
+      --set space.$sid \
+      background.color=0x40ffffff \
+      background.corner_radius=5 \
+      background.height=25 \
+      background.drawing=off \
+      icon="$space_icon" \
+      icon.padding_left=7 \
+      icon.padding_right=7 \
+      label.drawing=off \
+      click_script="aerospace workspace $sid" \
+      script="$BASH_PLUGIN_DIR/aerospace.sh $sid" # Ensure aerospace.sh exists at this path and is executable
+  done
+else
+  echo "SketchyBar: aerospace command not found. Skipping space indicators." >&2
+fi
 
 
 ##### Adding Right Items #####
-# In the same way as the left items we can add items to the right side.
-# Additional position (e.g. center) are available, see:
-# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar
-
-# Some items refresh on a fixed cycle, e.g. the clock runs its script once
-# every 10s. Other items respond to events they subscribe to, e.g. the
-# volume.sh script is only executed once an actual change in system audio
-# volume is registered. More info about the event system can be found here:
-# https://felixkratz.github.io/SketchyBar/config/events
-
 sketchybar --add item clock right \
-           --set clock update_freq=10 icon=  script="$PLUGIN_DIR/clock.sh" \
+           --set clock update_freq=10 icon=  script="lua $PLUGIN_DIR/clock.lua" \
            --add item volume right \
-           --set volume script="$PLUGIN_DIR/volume.sh" \
+           --set volume script="lua $PLUGIN_DIR/volume.lua" \
            --subscribe volume volume_change \
-           --add item network.up right \
-           --set network.up update_freq=1 script="$PLUGIN_DIR/network.sh" \
-           --add item network.down right \
-           --set network.down update_freq=1 script="$PLUGIN_DIR/network.sh" \
            --add item battery right \
-           --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
+           --set battery update_freq=120 script="lua $PLUGIN_DIR/battery.lua" \
            --subscribe battery system_woke power_source_change
 
-##### Force all scripts to run the first time (never do this in a script) #####
+##### Force all scripts to run the first time #####
 sketchybar --update
